spring:
  datasource:
    url: jdbc:tc:postgresql:16:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway gerencia o schema
    show-sql: false
  
  flyway: 
    enabled: true
    locations:
      - classpath:db/migration/common

# Redis
  cache:
    type: none

management:
  endpoints:
    web:
      exposure:
        exclude:
        - '*'
  
# JWT - valor de teste
jwt:
  secret-key: test-secret-key-for-integration-tests-that-must-be-at-least-256-bits-long-for-hs256
  access-token-seconds: 900 # 15 minutes
  refresh-token-days: 7 # 7 days

logging:
  level:
    '[com.example.library]': DEBUG
    '[org.springframework.security]': DEBUG