global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'library-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          environment: 'prod'
          service: 'library-api'

rule_files:
  - 'alerts.yml'