name: CI - Library API

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run unit tests + coverage
        run: ./gradlew clean test jacocoTestReport

      - name: Run integration tests + coverage
        run: ./gradlew integrationTest jacocoTestReport

      - name: Verify coverage threshold
        run: ./gradlew jacocoTestCoverageVerification

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml,build/reports/jacoco/integrationTest/jacocoIntegrationTestReport.xml

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: 330445999c5bbbbbbb69c0051da2c4c9b4d7e193
          SONAR_PROJECTKEY: erichiroshi_library-api
          SONAR_ORGANIZATION: erichiroshi
          SONAR_HOST_URL: https://sonarcloud.io
        run: ./gradlew sonar --info || echo "Sonar falhou, mas continuando..."

      - name: Build Docker image
        run: docker build -t library-api .